// movies
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'

export const CREATE_MOVIES_REQUEST = 'CREATE_MOVIES_REQUEST'
export const CREATE_MOVIES_SUCCESS = 'CREATE_MOVIES_SUCCESS'
export const CREATE_MOVIES_FAILURE = 'CREATE_MOVIES_FAILURE'

// reserves
export const GET_RESERVATIONS_REQUEST = 'GET_RESERVATIONS_REQUEST'
export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS'
export const GET_RESERVATIONS_FAILURE = 'GET_RESERVATIONS_FAILURE'

export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST'
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS'
export const CREATE_RESERVATION_FAILURE = 'CREATE_RESERVATION_FAILURE'
